name: Close Pull Request

# only trigger on pull request closed events
on:
  pull_request:
    types: [ closed ]

jobs:
  remove-pr-s3:
    name: Remove PR's S3 folder
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Cleanup
        run: aws s3 rm ${{ secrets.AWS_SECRET_S3_BUCKET }}/test/${{ github.event.number }} --recursive

  copy-playwright-report:
    name: Publish latest merged playwright report
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install azcopy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget

          # when ubuntu-latest changes this needs updating from 22.04
          wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y azcopy
          rm -f packages-microsoft-prod.deb

      - name: Copy playwright report from PR
        run: |
            azcopy copy "https://mysimplewebsite.blob.core.windows.net/playwright/${{github.event.pull_request.number}}/*?${{ secrets.AZURE_SAS_TOKEN }}"  "https://mysimplewebsite.blob.core.windows.net/playwright/master?${{ secrets.AZURE_SAS_TOKEN }}" --recursive=true

      - name: Remove PR playwright report from Azure
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az storage fs directory delete --account-name mysimplewebsite --file-system playwright --name ${{github.event.pull_request.number}} --yes

  copy-code-coverage-report:
    name: Publish latest merged code coverage report
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install azcopy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget

          # when ubuntu-latest changes this needs updating from 22.04
          wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y azcopy
          rm -f packages-microsoft-prod.deb

      - name: Copy PR coverage from PR
        run: |
            azcopy copy "https://mysimplewebsite.blob.core.windows.net/coverage/${{github.event.pull_request.number}}/*?${{ secrets.AZURE_SAS_TOKEN }}"  "https://mysimplewebsite.blob.core.windows.net/coverage/master?${{ secrets.AZURE_SAS_TOKEN }}" --recursive=true

      - name: Remove PR coverage from Azure
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az storage fs directory delete --account-name mysimplewebsite --file-system coverage --name ${{ github.event.pull_request.number }} --yes


