name: pr e2e test
on:
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  unit-test:
    name: unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm i

      - name: Run Angular unit test
        run: npm run test:karma

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload angular coverage report to Azure
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az storage blob upload-batch --account-name mysimplewebsite -s ./coverage -d angular-coverage --destination-path ${{github.event.pull_request.number}} --overwrite

      - name: Populate angular coverage report to job summary
        run: |
          echo "# Deployed angular coverage report to https://mysimplewebsite.blob.core.windows.net/angular-coverage/${{github.event.pull_request.number}}/simple-web-site/index.html" >> $GITHUB_STEP_SUMMARY

